FurnitureShop.Web/Areas/Admin/Controllers/OrdersController.cs
using FurnitureShop.DAL.Models;
using FurnitureShop.Web.Areas.Admin.Models.OrderModels;
using Microsoft.AspNetCore.Mvc;
using System;

namespace FurnitureShop.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class OrdersController : AdminController
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult _Order(int id)
        {
            var model = new OrderVM
            {
                OrderId = id
            };

            var order = UnitOfWork.Orders.FindById(id);
            model.UserId = order.UserId;
            model.Address = order.Address;
            model.City = order.City;
            model.Email = order.Email;
            model.FirstName = order.FirstName;
            model.LastName = order.LastName;
            model.OrderDeliveryTypeId = order.OrderDeliveryType;
            model.OrderPaymentTypeId = order.OrderPaymentType;
            model.OrderStatusId = order.OrderStatus;
            model.Phone = order.Phone;
            model.Region = order.Region;
            model.OrderDeliveryTypes = UnitOfWork.OrderDeliveryTypes.FindAll();
            model.OrderPaymentTypes = UnitOfWork.OrderPaymentTypes.FindAll();
            model.OrderStatuses = UnitOfWork.OrderStatuses.FindAll();
            model.OrderProducts = UnitOfWork.StoredProcedures.GetOrderProductsInfo(order.UserId, id);
            model.TotalSum = UnitOfWork.StoredProcedures.GetOrderSum(id);

            return PartialView(model);
        }
        [HttpGet]
        public IActionResult _OrderList(string search)
        {
            var orders = UnitOfWork.StoredProcedures.GetOrdersInfo_Admin(search);
            return PartialView(orders);
        }
        [HttpPost]
        public IActionResult ChangeOrderItemQuantity(int itemId, int orderId, int quantity)
        {
            bool success;
            string message = string.Empty;
            double itemTotal = 0;
            double total = 0;
            try
            {
                var orderItem = UnitOfWork.OrderProducts.FirstOrDefault(x => x.ItemId == itemId && x.OrderId == orderId);
                orderItem.Quantity = quantity;
                success = UnitOfWork.OrderProducts.Update(orderItem);
                itemTotal = quantity * orderItem.Price;
                total = UnitOfWork.StoredProcedures.GetOrderSum(orderId);
            }
            catch (Exception)
            {
                success = false;
                message = "При обновлении возникла ошибка!";
            }
            return Json(new { success, message, itemTotal, total });
        }
        [HttpPost]
        public IActionResult DeleteOrderItem(int itemId, int orderId)
        {
            bool success;
            string message = string.Empty;
            double total = 0;
            try
            {
                var orderItem = UnitOfWork.OrderProducts.FirstOrDefault(x => x.ItemId == itemId && x.OrderId == orderId);
                success = UnitOfWork.OrderProducts.Delete(orderItem);
                total = UnitOfWork.StoredProcedures.GetOrderSum(orderId);
            }
            catch (Exception)
            {
                success = false;
                message = "При удалении возникла ошибка!";
            }
            return Json(new { success, message, total });
        }
        [HttpPost]
        public IActionResult SaveOrderInfo(OrderVM orderVM)
        {
            bool success;
            string message = string.Empty;
            Order order = null;
            try
            {
                order = UnitOfWork.Orders.FindById(orderVM.OrderId);
                order.Address = orderVM.Address;
                order.City = orderVM.City;
                order.Email = orderVM.Email;
                order.FirstName = orderVM.FirstName;
                order.LastName = orderVM.LastName;
                order.OrderDeliveryType = orderVM.OrderDeliveryTypeId;
                order.OrderPaymentType = orderVM.OrderPaymentTypeId;
                order.OrderStatus = orderVM.OrderStatusId;
                order.Phone = orderVM.Phone;
                order.Region = orderVM.Region;
                success = UnitOfWork.Orders.Update(order);
            }
            catch (Exception)
            {
                success = false;
                message = "При удалении возникла ошибка!";
            }
            return Json(new { success, message, order });
        }
        [HttpPost]
        public IActionResult DeleteOrRestoreOrder(int id)
        {
            bool success;
            bool? isDeleted = null;
            try
            {
                var order = UnitOfWork.Orders.FindById(id);
                success = UnitOfWork.Orders.DeleteOrRestore(order);
                isDeleted = order.IsDeleted;
            }
            catch (Exception)
            {
                success = false;
            }

            return Json(new { success, isDeleted });
        }
    }
}

FurnitureShop.Web/Controllers/ShopController.cs
using FurnitureShop.DAL.Models.StoredProcedureModels;
using FurnitureShop.Web.Extensions;
using FurnitureShop.Web.Models.ShopModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace FurnitureShop.Web.Controllers
{
    public class ShopController : BaseController
    {
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index(int? categoryId = null, int? brandId = null, string search = null, string categoriesStr = null, int? minPrice = null, int? maxPrice = null)
        {
            var categories = categoriesStr?.Split(',').Select(int.Parse).AsEnumerable();

            var products = UnitOfWork.StoredProcedures.SearchItemInfo(SystemUser?.Id, brandId: brandId, categoryId: categoryId, minPrice: minPrice, maxPrice: maxPrice, search: search);
            var hasProducts = products.Count() == 0;
            var _minPrice = minPrice.HasValue ? minPrice.Value : hasProducts ? 0 : products.Min(x => x.Price);
            var _maxPrice = maxPrice.HasValue ? maxPrice.Value : hasProducts ? 0 : products.Max(x => x.Price);

            if (categories?.Count() > 0)
            {
                products = products.Where(x => UnitOfWork.StoredProcedures.CategoriesForProduct(x.ProductId).Any(y => categories.Contains(y.Id)));
            }

            var model = new IndexVM
            {
                Products = products.ChunkBy(6),
                CategoryHierarchy = UnitOfWork.StoredProcedures.GetCategoryHierarchy(),
                MinPrice = UnitOfWork.StoredProcedures.GetProductNumericValueByOption(ProductOption.MinPrice.GetDescription()),
                MaxPrice = UnitOfWork.StoredProcedures.GetProductNumericValueByOption(ProductOption.MaxPrice.GetDescription()),
                Search = search,
                SelectedMinPrice = minPrice,
                SelectedMaxPrice = maxPrice,
                Categories = categories
            };
            if (categoryId.HasValue)
            {
                model.Categories = new int[] { categoryId.Value };
            }
            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Product(int id)
        {
            var model = new ProductVM
            {
                Product = UnitOfWork.Products.FindById(id),
                Products = UnitOfWork.StoredProcedures.GetItemsInfo(8, userId: SystemUser?.Id),
                Categories = UnitOfWork.StoredProcedures.CategoriesForProduct(id),
                ProductImages = UnitOfWork.StoredProcedures.GetProductImages(id),
                Items = UnitOfWork.Items.Find(x => x.ProductId == id),
                ItemsWithParameters = UnitOfWork.StoredProcedures.GetItemWithParameters(id),
                Favourite = UnitOfWork.FavouriteProducts.Find(x => x.UserId == SystemUser?.Id && x.ProductId == id).Any()
            };
            return View(model);
        }

        [HttpGet]
        public IActionResult _Cart()
        {
            var model = new CartVM
            {
                CartItems = UnitOfWork.StoredProcedures.GetCartItemsInfo(SystemUser.Id)
            };
            return PartialView(model);
        }

        [HttpGet]
        public IActionResult _OrderProductInfo(int orderId)
        {
            var model = UnitOfWork.StoredProcedures.GetOrderProductsInfo(SystemUser.Id, orderId);
            return PartialView(model);
        }

        [HttpGet]
        public IActionResult Cart()
        {
            var model = new CartVM
            {
                CartItems = UnitOfWork.StoredProcedures.GetCartItemsInfo(SystemUser.Id)
            };
            return View(model);
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            var model = new CheckoutVM
            {
                CartItems = UnitOfWork.StoredProcedures.GetCartItemsInfo(SystemUser.Id),
                OrderDeliveryTypes = UnitOfWork.OrderDeliveryTypes.FindAll(),
                OrderPaymentTypes = UnitOfWork.OrderPaymentTypes.FindAll()
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Order(OrderVM model)
        {
            bool success;
            var message = string.Empty;
            try
            {
                if (ModelState.IsValid)
                {
                    success = UnitOfWork.StoredProcedures.CreateOrder(SystemUser.Id, model.DeliveryTypeId.Value, model.PaymentTypeId.Value,
                        model.Email, model.FirstName, model.LastName, model.Phone, model.Address, model.City, model.Region);
                }
                else
                {
                    success = false;
                    message = ModelState.GetHtmlErrors();
                    return Json(new { success, message });
                }
            }
            catch (System.Exception)
            {
                success = false;
            }
            if (success)
            {
                message = "Ваш заказ был создан. Наш менеджер скоро свяжется с вами!";
            }
            else
            {
                message = "При создании заказа произошла ошибка! Обратитесь в службу поддержку.";
            }

            return Json(new { success, message });
        }

        [HttpPost]
        public IActionResult AddToCart(int itemId, int? quantity = null)
        {
            bool success;
            var message = string.Empty;
            double cartTotal = 0;
            var item = (CartItemsInfo_Result)null;
            try
            {
                var isZero = quantity.HasValue && quantity.Value == 0;
                item = UnitOfWork.StoredProcedures.MergeItemToCart(SystemUser.Id, itemId, isZero ? null : quantity, isZero);
                cartTotal = UnitOfWork.StoredProcedures.GetCartSum(SystemUser.Id);
                success = true;
                message = "Товар добавлен в корзину!";
            }
            catch (System.Exception)
            {
                success = false;
                message = "При добавлении товара произошла ошибка! Обратитесь в службу поддержку.";
            }

            return Json(new { success, message, item, cartTotal });
        }

        [HttpPost]
        public IActionResult RemoveFromCart(int itemId)
        {
            bool success;
            var message = string.Empty;
            try
            {
                UnitOfWork.StoredProcedures.MergeItemToCart(SystemUser.Id, itemId, isDeleted: true);
                success = true;
                message = "Товар удален из корзины!";
            }
            catch (System.Exception)
            {
                success = false;
                message = "При добавлении товара произошла ошибка! Обратитесь в службу поддержку.";
            }

            return Json(new { success, message });
        }
    }
}

FurnitureShop.Web/Areas/Admin/Views/Orders/_Order.cshtml
@model FurnitureShop.Web.Areas.Admin.Models.OrderModels.OrderVM
@using static FurnitureShop.Web.Extensions.ImagePathExtension
@{
}
<div class="container">
    <input type="hidden" id="order-id" value="@Model.OrderId" />
    <input type="hidden" id="user-id" value="@Model.UserId" />
    <!-- Info Start -->
    <div class="form-row" id="order-info">
        <div class="form-group col-md-6 col-12">
            <label for="firstName">Имя:</label>
            <input type="text" class="form-control" id="firstName" readonly value="@Model.FirstName">
        </div>
        <div class="form-group col-md-6 col-12">
            <label for="lastName">Имя:</label>
            <input type="text" class="form-control" id="lastName" readonly value="@Model.LastName">
        </div>
        <div class="form-group col-lg-6 col-md-12 col-12">
            <label for="address">Адрес:</label>
            <input type="text" class="form-control" id="address" readonly value="@Model.Address">
        </div>
        <div class="form-group col-lg-3 col-md-6 col-12">
            <label for="city">Город:</label>
            <input type="text" class="form-control" id="city" readonly value="@Model.City">
        </div>
        <div class="form-group col-lg-3 col-md-6 col-12">
            <label for="region">Область:</label>
            <input type="text" class="form-control" id="region" readonly value="@Model.Region">
        </div>
        <div class="form-group col-md-8 col-12">
            <label for="email">Email:</label>
            <input type="text" class="form-control" id="email" readonly value="@Model.Email">
        </div>
        <div class="form-group col-md-4 col-12">
            <label for="phone">Телефон:</label>
            <input type="text" class="form-control" id="phone" readonly value="@Model.Phone">
        </div>
    </div>
    <div class="btn-group-toggle text-right" data-toggle="buttons">
        <label class="btn btn-outline-dark">
            <input type="checkbox" autocomplete="off" id="edit-order-info" />
            <i class="fa fa-pen"></i>
        </label>
    </div>
    <div class="form-row">
        <div class="form-group col-lg-4 col-md-12">
            <label for="orderStatusId">Статус:</label>
            <select class="form-control" id="orderStatusId">
                @foreach (var status in Model.OrderStatuses)
                {
                    <option value="@status.Id" @(status.Id == Model.OrderStatusId ? " selected" : null)>@status.Status</option>
                }
            </select>
        </div>
        <div class="form-group col-lg-4 col-md-12">
            <label for="orderPaymentTypeId">Тип оплаты:</label>
            <select class="form-control" id="orderPaymentTypeId">
                @foreach (var type in Model.OrderPaymentTypes)
                {
                    <option value="@type.Id" @(type.Id == Model.OrderPaymentTypeId ? " selected" : null)>@type.Type</option>
                }
            </select>
        </div>
        <div class="form-group col-lg-4 col-md-12">
            <label for="orderDeliveryTypeId">Доставка:</label>
            <select class="form-control" id="orderDeliveryTypeId">
                @foreach (var type in Model.OrderDeliveryTypes)
                {
                    <option value="@type.Id" @(type.Id == Model.OrderDeliveryTypeId ? " selected" : null)>@type.Type</option>
                }
            </select>
        </div>
    </div>
    <div class=" mb-3 text-right">
        <button type="button" class="btn btn-outline-success" id="save-order-info">Сохранить</button>
    </div>
    <!-- Info End -->
    <!-- Products Start -->
    <table class="table table-sm table-hover table-responsive table-centered">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col" width="15%"></th>
                <th scope="col">Наименование</th>
                <th scope="col">Цена(шт.)</th>
                <th scope="col">Кол-во</th>
                <th scope="col">Сумма</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model.OrderProducts)
            {
                <tr class="product-row" data-item-id="@product.ItemId">
                    <th scope="row">
                        <a href="@Url.Action("Product","Shop", new { area = string.Empty, id = product.ProductId })" target="_blank">
                            @product.ProductId
                        </a>
                    </th>
                    <td>
                        <a href="@Url.Action("Product","Shop", new { area = string.Empty, id = product.ProductId })" target="_blank">
                            <img class="img-thumbnail" src="~/@ProductImage(product.Image)" alt="@product.Name" />
                        </a>
                    </td>
                    <td>
                        <a href="@Url.Action("Product","Shop", new { area = string.Empty, id = product.ProductId })" target="_blank">
                            @product.Name
                        </a>
                    </td>
                    <td>@product.Price</td>
                    <td><input class="form-control" type="number" name="quantity" value="@product.Quantity" min="0" /></td>
                    <td class="product-total">@product.Total</td>
                    <td class="order-product-delete"><i class="pointer fa fa-trash-alt text-danger"></i></td>
                </tr>
            }
            <tr>
                <th scope="row"></th>
                <td></td>
                <td></td>
                <td></td>
                <td class="font-weight-bold" style="text-align:right!important;">Итого:</td>
                <td class="font-weight-bold" id="total-sum">@Model.TotalSum</td>
                <td></td>
            </tr>
        </tbody>
    </table>
    <!-- Products End -->
</div>
<script>
    $('#save-order-info').click(function () {
        var data = { orderId: $('input#order-id').val() };
        $('.form-row input,select').each(function (i, el) {
            data[$(el).attr('id')] = $(el).val();
        });
        $.ajax({
            method: 'POST',
            url: '@Url.Action("SaveOrderInfo", "Orders", new { area = "Admin"})',
            data: data,
            success: function (data) {
                if (data.success) {
                    search();
                    Swal.fire({
                        type: 'success',
                        title: 'Обновлено',
                        text: 'Детали заказа были успешно изменены!',
                        showConfirmButton: false,
                        timer: 2000
                    });
                } else {
                    Swal.fire({
                        type: 'error',
                        title: 'Ошибка',
                        text: 'При обновлении заказа произошла ошибка!',
                        showConfirmButton: false,
                        timer: 2000
                    });
                }
            }
        });
    });
    $('#edit-order-info').change(function () {
        if ($(this).is(':checked')) {
            $('#order-info input').attr('readonly', null);
        } else {
            $('#order-info input').attr('readonly', 'readonly');
        }
    });
    $('.product-row .order-product-delete').click(function () {
        var parent = $(this).parents('tr');
        var orderId = $('input#order-id').val();
        var itemId = parent.data('item-id');
        Swal.fire({
            type: 'warning',
            title: 'Удаление',
            text: 'Вы уверены, что хотите удалить этот товар из заказа?',
            showConfirmButton: true,
            showCancelButton: true,
            confirmButtonText: 'Да',
            cancelButtonText: 'Отмена'
        }).then((result) => {
            if (result.value) {
                $.ajax({
                    method: 'POST',
                    url: '@Url.Action("DeleteOrderItem", "Orders", new { area = "Admin" })',
                    data: { orderId: orderId, itemId: itemId },
                    success: function (data) {
                        if (data.success) {
                            search();
                            Swal.fire({
                                type: 'success',
                                title: 'Удалено',
                                text: 'Товар был успешно удален!',
                                showConfirmButton: false,
                                timer: 2000
                            });
                            parent.fadeOut().remove();
                        } else {
                            Swal.fire({
                                type: 'error',
                                title: 'Ошибка',
                                text: 'При удалении произошла ошибка!',
                                showConfirmButton: false,
                                timer: 2000
                            });
                        }
                    }
                });
            }
        });
    });
    $('.product-row input[name="quantity"]').bind('keyup mouseup', function () {
        var _this = $(this);
        var parent = _this.parents('tr');
        var value = _this.val();
        var orderId = $('input#order-id').val();
        var itemId = parent.data('item-id');
        if (!isNaN(value)) {
            if (value > 0) {
                $.ajax({
                    method: 'POST',
                    url: '@Url.Action("ChangeOrderItemQuantity", "Orders", new { area = "Admin" })',
                    data: { orderId: orderId, itemId: itemId, quantity: value },
                    success: function (data) {
                        search();
                        $('#total-sum').text(data.total);
                        _this.parent().siblings('.product-total').text(data.itemTotal);
                    }
                });
            } else {
                Swal.fire({
                    type: 'warning',
                    title: 'Удаление',
                    text: 'Вы уверены, что хотите удалить этот товар из заказа?',
                    showConfirmButton: true,
                    showCancelButton: true,
                    confirmButtonText: 'Да',
                    cancelButtonText: 'Отмена'
                }).then((result) => {
                    if (result.value) {
                        $.ajax({
                            method: 'POST',
                            url: '@Url.Action("DeleteOrderItem", "Orders", new { area = "Admin" })',
                            data: { orderId: orderId, itemId: itemId },
                            success: function (data) {
                                if (data.success) {
                                    search();
                                    Swal.fire({
                                        type: 'success',
                                        title: 'Удалено',
                                        text: 'Товар был успешно удален!',
                                        showConfirmButton: false,
                                        timer: 2000
                                    });
                                    parent.fadeOut().remove();
                                } else {
                                    Swal.fire({
                                        type: 'error',
                                        title: 'Ошибка',
                                        text: 'При удалении произошла ошибка!',
                                        showConfirmButton: false,
                                        timer: 2000
                                    });
                                }
                            }
                        });
                    }
                    _this.val(1);
                });
            }
        }
    });
</script>

FurnitureShop.Web/Areas/Admin/Views/Orders/_OrderList.cshtml
@model IEnumerable<FurnitureShop.DAL.Models.StoredProcedureModels.GetOrdersInfo_Admin_Result>

<table class="table table-sm table-hover table-centered for-data-table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Покупатель</th>
            <th scope="col">Кол-во</th>
            <th scope="col">Сумма</th>
            <th scope="col">Город</th>
            <th scope="col">Статус</th>
            <th scope="col">Доставка</th>
            <th scope="col">Оплата</th>
            <th scope="col">Создан</th>
            <th scope="col">Изменен</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @if (Model?.Count() > 0)
        {
            @foreach (var order in Model)
            {
                <tr class="order-row pointer" data-order-id="@order.OrderId" data-is-deleted="@order.IsDeleted">
                    <th scope="row">@order.OrderId</th>
                    <td>@order.Customer</td>
                    <td>@order.ItemsCount</td>
                    <td>@order.TotalSum</td>
                    <td>@order.OrderCity</td>
                    <td>@order.Status</td>
                    <td>@order.OrderDeliveryType</td>
                    <td>@order.OrderPaymentType</td>
                    <td>@order.DateCreated.ToShortDateString()</td>
                    <td>@order.DateModified.ToShortDateString()</td>
                    <td class="order-delete-restore"><i class="pointer fa @(order.IsDeleted ? "fa-trash-restore-alt text-success" : "fa-trash-alt text-danger")"></i></td>
                </tr>
            }
        }
    </tbody>
</table>

<script>$('.for-data-table').DataTable();</script>